export type CopyStatus = "draft" | "machine_translated" | "reviewed" | "published";

export type CopyToken = {
  key: string;
  namespace: "home" | "weather" | "guidance" | "forecast" | "source";
  sourceEn: string;
  si: string;
  ta: string;
  status: CopyStatus;
  cmsEditable: boolean;
  context: string;
  trigger?: string;
};

export const copyTokens = [
  {
    key: "home.eyebrow",
    namespace: "home",
    sourceEn: "Kunatu · Yan public beta",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Small label above the main location/signal hero.",
  },
  {
    key: "home.disclaimer.short",
    namespace: "home",
    sourceEn: "Practical forecast guidance, not an official warning.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Short public disclaimer shown near the main signal and footer.",
  },
  {
    key: "home.location.label",
    namespace: "home",
    sourceEn: "Location",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Label for the public location selector.",
  },
  {
    key: "home.location.update",
    namespace: "home",
    sourceEn: "Update",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Submit button for the public location selector.",
  },
  {
    key: "weather.now",
    namespace: "weather",
    sourceEn: "Now",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Label for current weather conditions.",
  },
  {
    key: "weather.feels",
    namespace: "weather",
    sourceEn: "Feels",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Label before apparent temperature.",
  },
  {
    key: "weather.metric.rain_chance",
    namespace: "weather",
    sourceEn: "Rain chance",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Metric label for precipitation probability.",
  },
  {
    key: "weather.metric.rain_now",
    namespace: "weather",
    sourceEn: "Rain now",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Metric label for current precipitation amount.",
  },
  {
    key: "weather.metric.humidity",
    namespace: "weather",
    sourceEn: "Humidity",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Metric label for humidity.",
  },
  {
    key: "weather.metric.wind",
    namespace: "weather",
    sourceEn: "Wind",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Metric label for wind speed.",
  },
  {
    key: "weather.advisory.signal",
    namespace: "weather",
    sourceEn: "Advisory signal",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Label for Kunatu heuristic advisory state.",
  },
  {
    key: "guidance.section.eyebrow",
    namespace: "guidance",
    sourceEn: "Practical guidance",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Eyebrow for practical suggestion cards.",
  },
  {
    key: "guidance.section.title",
    namespace: "guidance",
    sourceEn: "What to plan around",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Heading for practical suggestion cards.",
  },
  {
    key: "forecast.section.eyebrow",
    namespace: "forecast",
    sourceEn: "Forecast signal",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Eyebrow for the public hourly forecast section.",
  },
  {
    key: "source.updated",
    namespace: "source",
    sourceEn: "Updated",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Label before data freshness timestamp.",
  },
  {
    key: "forecast.next12.title",
    namespace: "forecast",
    sourceEn: "Next 12 hours",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Heading for the hourly forecast strip.",
  },
  {
    key: "forecast.next12.subtitle",
    namespace: "forecast",
    sourceEn: "Rain chance, temperature, and wind at a glance.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Subtitle for the hourly forecast strip.",
  },
  {
    key: "radar.eyebrow",
    namespace: "source",
    sourceEn: "Rain radar",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Eyebrow label for the RainViewer/MapLibre radar section.",
  },
  {
    key: "radar.title",
    namespace: "source",
    sourceEn: "Rain movement near Sri Lanka",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Title for the RainViewer/MapLibre radar section.",
  },
  {
    key: "radar.disclaimer",
    namespace: "source",
    sourceEn: "Observed radar and short-term projection from RainViewer. Use this as practical context, not as an official warning.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Source and safety explanation for the RainViewer radar map.",
  },
  {
    key: "radar.observed.label",
    namespace: "source",
    sourceEn: "Observed radar",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Timeline label for past RainViewer frames.",
  },
  {
    key: "radar.projection.label",
    namespace: "source",
    sourceEn: "Short-term projection",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Timeline label for RainViewer nowcast frames.",
  },
  {
    key: "radar.control.previous",
    namespace: "source",
    sourceEn: "Prev",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Button label for previous radar frame.",
  },
  {
    key: "radar.control.play",
    namespace: "source",
    sourceEn: "Play",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Button label for playing radar animation.",
  },
  {
    key: "radar.control.pause",
    namespace: "source",
    sourceEn: "Pause",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Button label for pausing radar animation.",
  },
  {
    key: "radar.control.next",
    namespace: "source",
    sourceEn: "Next",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Button label for next radar frame.",
  },
  {
    key: "radar.status.loading",
    namespace: "source",
    sourceEn: "Loading",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Radar metadata loading state.",
  },
  {
    key: "radar.status.unavailable",
    namespace: "source",
    sourceEn: "Unavailable",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Radar metadata error state.",
  },
  {
    key: "guidance.umbrella.high",
    namespace: "guidance",
    sourceEn: "Carry an umbrella. Showers look likely in the next few hours.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Practical suggestion card for high short-term rain probability.",
    trigger: "next6h.precipitationProbability >= 60 or next6h.precipitation >= 1mm",
  },
  {
    key: "guidance.umbrella.light",
    namespace: "guidance",
    sourceEn: "Small umbrella is worth it. Rain signal is mixed, but not zero.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Practical suggestion card for mixed but meaningful rain probability.",
    trigger: "next6h.precipitationProbability between 35 and 59",
  },
  {
    key: "guidance.hydration.hot_humid",
    namespace: "guidance",
    sourceEn: "Keep water close. It may feel sticky and warmer than the number shows.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Practical suggestion card for heat and humidity.",
    trigger: "apparentTemperature >= 31 and humidity >= 75",
  },
  {
    key: "guidance.roads.low_lying",
    namespace: "guidance",
    sourceEn: "Watch low-lying roads if showers intensify.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Practical suggestion card for rain that may affect movement.",
    trigger: "current.precipitation >= 3mm or next6h rain signal is high",
  },
  {
    key: "guidance.wind.breezy",
    namespace: "guidance",
    sourceEn: "Expect breezy patches. Secure light items before heading out.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Practical suggestion card for wind or gusty conditions.",
    trigger: "windSpeed >= 25km/h or windGust >= 35km/h",
  },
  {
    key: "guidance.laundry.risky",
    namespace: "guidance",
    sourceEn: "Not a great drying window. Keep laundry easy to pull in.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Lifestyle suggestion card for drying clothes.",
    trigger: "next8h rain chance >= 40 or humidity >= 85",
  },
  {
    key: "guidance.commute.rain",
    namespace: "guidance",
    sourceEn: "Leave a little early if rain lines up with your commute.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Movement suggestion card for rain near commuting windows.",
    trigger: "next3h rain chance >= 60 or current rain > 0",
  },
  {
    key: "guidance.evening.okay",
    namespace: "guidance",
    sourceEn: "Evening plans look okay for now. Recheck before leaving.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Low-risk suggestion card when evening conditions look manageable.",
    trigger: "5pm-10pm rain chance < 40 and wind < 30km/h",
  },
  {
    key: "guidance.low.check_again",
    namespace: "guidance",
    sourceEn: "No strong signal right now. Recheck before outdoor plans.",
    si: "",
    ta: "",
    status: "draft",
    cmsEditable: true,
    context: "Fallback suggestion when no strong rain, wind, or heat signal is visible.",
  },
] satisfies CopyToken[];

export function getCopy(key: string) {
  return copyTokens.find((token) => token.key === key)?.sourceEn ?? key;
}
